theme: jekyll-theme-cayman

# Site Settings
title: "Michael Grogan"
name: "Michael Grogan"
description: "Data Science Consultant with expertise in economics, time series analysis, and Bayesian methods"
